# Gradle / AndroidX settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# Allow building in paths with non-ASCII characters (e.g. C:\Users\Jiří\…)
# See: http://b.android.com/95744
android.overridePathCheck=true
