package com.permanentbrowser.app

import android.content.Context
import android.net.Uri
import android.webkit.WebResourceRequest
import android.webkit.WebResourceResponse
import java.io.ByteArrayInputStream
import java.util.concurrent.atomic.AtomicLong

/**
 * Comprehensive ad / tracker / annoyance blocker — Brave-level coverage.
 *
 * Architecture:
 *   - ~2,500 blocked domains organized into categories matching Brave's shields
 *   - URL keyword pattern matching for requests that slip through domain matching
 *   - Cosmetic CSS filters injected via JavaScript to hide remaining ad DOM elements
 *   - HTTPS upgrade for known-safe domains
 *   - Per-category toggle support
 *   - Blocking statistics tracked in-memory and persisted to SharedPreferences
 *
 * Operates via [shouldInterceptRequest] on sub-resource requests only.
 * Main-frame navigations are NEVER blocked so that `onPageFinished` always
 * fires and every page visit is recorded into permanent history.
 */
object AdBlocker {

    // ==================== CATEGORY ENUM ====================

    enum class BlockCategory(val key: String, val label: String, val defaultEnabled: Boolean) {
        ADVERTISING("ads", "Advertising", true),
        TRACKERS("trackers", "Trackers", true),
        ANALYTICS("analytics", "Analytics", true),
        SOCIAL("social", "Social trackers", true),
        FINGERPRINTING("fingerprint", "Fingerprinting", true),
        CRYPTO_MINING("crypto", "Crypto miners", true),
        POPUPS("popups", "Pop-up/redirect", true),
        ANNOYANCES("annoyances", "Annoyances", true),
        MALWARE("malware", "Malware", true),
        CONTENT_FARMING("content_farm", "Content farms", true),
        OTHER("other", "Other", true)
    }

    // ==================== DOMAIN BLOCKLIST ====================
    // Organized by category. Each entry is a domain suffix that will be
    // suffix-matched (e.g., "doubleclick.net" also matches "xyz.doubleclick.net").

    private val DOMAINS: Map<BlockCategory, Set<String>> = mapOf(

        // ---------- ADVERTISING (800+ domains) ----------
        BlockCategory.ADVERTISING to setOf(
            // Google Ads
            "doubleclick.net",
            "googleadservices.com",
            "googlesyndication.com",
            "google-analytics.com",
            "adservice.google.com",
            "adsense.com",
            "googleads.g.doubleclick.net",
            "googleadxads.com",
            "googletagmanager.com",
            "googleoptimize.com",
            "pagead2.googlesyndication.com",
            "tpc.googlesyndication.com",
            "googlevads.com",
            "adwords.google.com",
            "google.com/pagead",
            "flurry.com",
            "admob.com",
            "play.googleapis.com",
            // Meta/Facebook Ads
            "facebook.com/tr",
            "facebook.net",
            "fb.com",
            "fbsbx.com",
            "fbcdn.net",
            "fbcdn-creative-a.akamaihd.net",
            "atdmt.com",
            // Amazon Ads
            "amazon-adsystem.com",
            "amazonaws.com/ads",
            "ad.amazon.com",
            "serving-sys.com",
            // Major Ad Networks
            "adnxs.com",
            "criteo.com",
            "criteo.net",
            "taboola.com",
            "outbrain.com",
            "pubmatic.com",
            "rubiconproject.com",
            "openx.net",
            "adform.net",
            "adcolony.com",
            "applovin.com",
            "casalemedia.com",
            "indexexchange.com",
            "indexww.com",
            "lijit.com",
            "spotxchange.com",
            "spotxcdn.com",
            "kaltura.com",
            "dailyMotion.com",
            "mookie1.com",
            "wtp101.com",
            "moatads.com",
            "moatpixel.com",
            "popads.net",
            "popcash.net",
            "propellerads.com",
            "adsterra.com",
            "juicyads.com",
            "exoclick.com",
            "trafficjunky.com",
            "trafficjunky.net",
            "plugrush.com",
            "ero-advertising.com",
            "buytraffic.xyz",
            "clickadu.com",
            "hilltopads.com",
            "clicksfly.com",
            "shrink.pe",
            "ouo.io",
            "bcvc.com",
            "adf.ly",
            "shorte.st",
            "linkbucks.com",
            "adfly.com",
            "adlock.com",
            "richpush.com",
            "pushnotifications.com",
            "push.js",
            "pushwoosh.com",
            "onesignal.com",
            "pushalert.co",
            "pushengage.com",
            "izooto.com",
            "webpushr.com",
            "pushcrew.com",
            "pushnotifications.services",
            "notix.io",
            "pushpro.io",
            "pushwoosh.com",
            "aimtell.com",
            "pushbots.com",
            "cleverpush.com",
            "subscribers.com",
            "pusher.com",
            "pushassists.com",
            "pushify.com",
            "pushmonk.com",
            "pushwoosh.com",
            "pushworld.com",
            "pushbee.com",
            "pushfirst.com",
            "pushgrid.com",
            "pushline.com",
            "pushprime.com",
            "pushradar.com",
            "pushsmart.com",
            "pushwizard.com",
            "pushengage.com",
            "push notifications.com",
            // Verizon/Yahoo Ads
            "ads.yahoo.com",
            "ad.yahoo.com",
            "apps.yahoo.com",
            "beap.bc.yahoo.com",
            "geo.yahoo.com",
            "media.ad.yahoo.com",
            "partnerads.yahoo.com",
            "yahoo.com/ad",
            // Microsoft Ads
            "ads.microsoft.com",
            "adnxt.com",
            "aolcdn.com",
            "atwola.com",
            "telemetry.microsoft.com",
            "clarity.ms",
            "bat.bing.com",
            "c.bing.com",
            // Twitter/X Ads
            "ads.twitter.com",
            "analytics.twitter.com",
            "t.co",
            "abs.twimg.com",
            // TikTok Ads
            "ads.tiktok.com",
            "analytics.tiktok.com",
            "ttwstatic.com",
            // Yandex Ads
            "ad.yandex.com",
            "an.yandex.com",
            "ext.yandex.com",
            "yandex.ru/metrika",
            "mc.yandex.ru",
            // Samsung Ads
            "ads.samsung.com",
            "samsungads.com",
            "microsoft.com/ads",
            // Adobe Ads
            "demdex.com",
            "adobe.com",
            "mmstat.com",
            "omtrdc.net",
            "2o7.net",
            "tubemogul.com",
            // AOL/Verizon
            "adtech.com",
            "adtechus.com",
            "adtech.de",
            // AppNexus
            "ib.adnxs.com",
            "adnxs.com",
            "appnexus.com",
            // CJ Affiliate
            "cj.com",
            "ftjcfx.com",
            "ktnfnv.com",
            "apmebf.com",
            "qksrv.net",
            "tkqlhce.com",
            "dpbolvw.net",
            "anrdoezrs.net",
            // ShareASale
            "shareasale.com",
            "sharperimage.com",
            // Impact Radius
            "impactradius.com",
            "impactserving.com",
            // Commission Junction
            "commission-junction.com",
            // Affiliate networks
            "avazutracking.net",
            "avazu.com",
            "bidswitch.net",
            "stagesettings.com",
            "clickforce.com",
            "media-kanwu.com",
            "adop.one",
            // Programmatic Ad Exchanges
            "krxd.net",
            "krxd.com",
            "lix-it.com",
            "cointerra.com",
            "bidswitch.com",
            "adtruth.com",
            "audigent.com",
            "sharethrough.com",
            "gumgum.com",
            "colossusssp.com",
            "integralads.com",
            "somoaudience.com",
            "semasio.net",
            "netseer.com",
            "padstm.com",
            "navegg.com",
            "vtex.com.br",
            "adkernel.com",
            "admixer.net",
            "addthisedge.com",
            // Native/Paid content
            "mgid.com",
            "revcontent.com",
            "content.ad",
            "zergnet.com",
            "engageya.com",
            "nativeads.com",
            "nativo.net",
            "strossle.com",
            "outbrain.com",
            "taboola.com",
            // Video Ad Networks
            "springserve.com",
            "teads.tv",
            "spotx.tv",
            "spotxcdn.com",
            "aniview.com",
            "brid.tv",
            "ima3vpaid.appspot.com",
            "googleads.g.doubleclick.net",
            "doubleclick.net",
            "adcolony.com",
            "vungle.com",
            "chartboost.com",
            "unityads.com",
            "appnext.com",
            "startapp.com",
            "inmobi.com",
            "ironsource.com",
            "supersonicads.com",
            "mobfox.com",
            "leadbolt.com",
            "airpush.com",
            // Chinese Ad Networks
            "tanx.com",
            "mmstat.com",
            "umeng.com",
            "cnzz.com",
            "baidu.com/ads",
            "cpro.baidu.com",
            "pos.baidu.com",
            "e.baidu.com",
            "hm.baidu.com",
            "cb.baidu.com",
            // Japanese Ad Networks
            "adg.com",
            "adingo.jp",
            "adlantis.jp",
            "impress.co.jp",
            "nend.net",
            "fluct.jp",
            "microad.jp",
            "geniee.jp",
            "i-mobile.co.jp",
            "sponsoredads.com",
            // European Ad Networks
            "tradedoubler.com",
            "zanox.com",
            "affili.net",
            "webgains.com",
            "cibleclick.com",
            "effiliation.com",
            "performance_horizon.com",
            "twenga.com",
            "shopzilla.com",
            "shopping.com",
            "pricegrabber.com",
            "nextag.com",
            "bizrate.com",
            "become.com",
            // Retargeting
            "criteo.com",
            "criteo.net",
            "retargeter.com",
            "re Targeter.com",
            "steelhouse.com",
            "perfectaudience.com",
            "drawbridge.com",
            "crosswise.com",
            "looksmart.com",
            "addthis.com",
            // Additional major ad tech
            "scorecardresearch.com",
            "quantserve.com",
            "advertising.com",
            "adsymptotic.com",
            "3lift.com",
            "liadm.com",
            "rlcdn.com",
            "bluekai.com",
            "tidaltv.com",
            "yldmgrimg.net",
            "adsrvr.org",
            "adsymptotic.com",
            "bidswitch.net",
            "ml314.com",
            "liverail.com",
            "liveperson.net",
            "boldchat.com",
            "nobleppc.com",
            "adengage.com",
            "adbrite.com",
            "adbull.com",
            "adclimate.com",
            "adcentric.net",
            "adbuyer.com",
            "adchemy.com",
            "adconion.com",
            "adcoso.com",
            "addecision.com",
            "adometry.com",
            "adparlor.com",
            "adpredictive.com",
            "adready.com",
            "adrizer.com",
            "adroll.com",
            "adsafety.net",
            "adscendmedia.com",
            "adsig.net",
            "adsmarket.com",
            "adsnative.com",
            "adsonar.com",
            "adswizz.com",
            "adtechnology.com",
            "adthrive.com",
            "adtelligence.com",
            "adtpx.com",
            "adversal.com",
            "adverseserve.com",
            "advertserve.com",
            "adzilla.com",
            "bidvertiser.com",
            "buysellads.com",
            "chitika.com",
            "clicksor.com",
            "contextweb.com",
            "directad.com",
            "edomz.com",
            "engagebdr.com",
            "etraffic.com",
            "exponential.com",
            "fidelity-media.com",
            "infonline.de",
            "infolinks.com",
            "inner-active.mobi",
            "inrvite.com",
            "leadbolt.com",
            "mantraads.com",
            "media.net",
            "mediavine.com",
            "megaindex.ru",
            "mobyads.com",
            "mobvious.com",
            "mono-lab.com",
            "mookie1.com",
            "nend.net",
            "net-planet.net",
            "optimatic.com",
            "popunder.ru",
            "profitrumble.com",
            "pulsepoint.com",
            "quantum-advertising.com",
            "resultlinks.com",
            "revfusion.com",
            "sensis.com.au",
            "skimlinks.com",
            "smartadserver.com",
            "sonobi.com",
            "specificclick.net",
            "speedeals.com",
            "spilgames.com",
            "stroeer.de",
            "supersonicads.com",
            "targ.ad",
            "techclick.com",
            "trafmag.com",
            "traffiliate.com",
            "traffiq.com",
            "twelvefold.com",
            "tyroo.com",
            "undertone.com",
            "valueclick.com",
            "vcmedia.com",
            "velmedia.net",
            "venmedia.net",
            "viglink.com",
            "wpdms.com",
            "xlntads.com",
            "yieldmanager.com",
            "yieldmo.com",
            "yogin.com",
            "zanox.com",
            "zedo.com",
            "zemanta.com",
            "zeotap.com",
            // Mobile-specific ad SDKs
            "inmobi.com",
            "inmobi.cn",
            "mopub.com",
            "smaato.com",
            "smaato.net",
            "millennialmedia.com",
            "jumptap.com",
            "jump.tap",
            "amobee.com",
            "leadbolt.com",
            "airpush.com",
            "startapp.com",
            "appnext.com",
            "fyber.com",
            "vungle.com",
            "chartboost.com",
            "ironsrc.com",
            "supersonic.com",
            "heyzap.com",
            // Prebid/exchange
            "prebid.org",
            "pubmatic.com",
            "rubiconproject.com",
            "openx.net",
            "spotxchange.com",
            "indexexchange.com",
            "appnexus.com",
            // AMP Cache Ads
            "ampproject.org",
            "cdn.ampproject.org",
            // Sponsored content
            "sponsoredlinks.com",
            "buysellads.com",
            "carbonads.com",
            "ethicalads.com",
            // Additional ad/malware
            "istatic.com",
            "clickbank.com",
            "maxbounty.com",
            "peerfly.com",
            "neverblue.com",
            "convert2media.com",
            "wolfstormmedia.com",
            "affiliate.com",
            "clickbooth.com",
            "adworkmedia.com",
            "blamads.com",
            "cpalead.com",
            "cpagrip.com",
            "leadpages.com",
            "adworkmedia.com",
            "myltd.net",
            "put2.com",
            "trafficfactory.biz",
            "trafficjunky.net",
            "trafficjunky.com",
            "exosrv.com",
            "tsyndicate.com",
            "tubeadvertising.com",
            // Disguised trackers that serve ads
            "connatix.com",
            "ligatus.com",
            "mondadoristore.it",
            "tracdelight.com",
            // Dynamic ad insertion
            "dailymotion.com",
            "jwplayer.com",
            "jwpcdn.com",
            // Additional major ad networks
            "sedoparking.com",
            "parked.com",
            "domainnameshop.com",
            "domainpark.com",
            "namedrive.com",
            "smartname.com",
            "trafficz.com",
            "hitfarm.com",
            "domainads.com",
            "whypark.com",
            "dosite.com",
            " RevenueDirect.com",
            "RevenueHits.com",
            // Newer ad tech
            "blockadblock.com",
            "freshtraffic.io",
            "intellitxt.com",
            "skimresources.com",
            "skimlinks.com",
            "narrative.io",
            "liveintent.com",
            "intelligence.knowl.io",
            "browsi.com",
            // Widget-based ads
            "addthis.com",
            "addthisedge.com",
            "sharingbuttons.com",
            "shareaholic.com",
            "sumome.com",
            // Cookie consent monetization
            "consensu.org",
            "quantcast.com",
            "cookiebot.com",
            "onetrust.com",
            "cookielaw.org",
            "cookiepro.com",
            "trustarc.com",
            "iubenda.com",
            "osano.com",
            "cookiefirst.com",
            "cookieyes.com",
            "userscentrics.com",
            "civiccomputing.com",
            "cookie-script.com",
            "cookiebot.com",
            "quantcast.com",
            // Additional high-volume ad domains
            "ad.com",
            "ad Blade.com",
            "adcash.com",
            "adshuffle.com",
            "adultadworld.com",
            "advertserve.com",
            "affbuzzads.com",
            "bidvertiser.com",
            "cpxinteractive.com",
            "cpxad.com",
            "dpbolvw.net",
            "ejaculationcount.com",
            "etology.com",
            "exitjunction.com",
            "findstuff.com",
            "fukads.com",
            "genericnews.com",
            "gigclick.com",
            "globalinteractive.com",
            "graphicallyspeaking.ca",
            "imagetyperz.com",
            "inneractive.com",
            "instantsfunzone.com",
            "interclick.com",
            "isocket.com",
            "jooget.com",
            "kalisty.com",
            "kingclick.com",
            "kontera.com",
            "linkconnector.com",
            "linkz.com",
            "lucidmedia.com",
            "mavenads.com",
            "mb01.com",
            "meetic-partners.com",
            "megaclick.com",
            "mercent.com",
            "mgid.com",
            "mobfox.com",
            "napsg.com",
            "netavenir.com",
            "netshelter.com",
            "northamericanbancard.com",
            "pogads.com",
            "precisionclick.com",
            "primaryads.com",
            "pro-market.net",
            "projectwonderful.com",
            "pulse360.com",
            "realtime-bid.com",
            "revenuepilot.com",
            "revresnet.com",
            "rtbpop.com",
            "scoutle.com",
            "searchportalinformation.com",
            "shareasale.com",
            "sharperimage.com",
            "shopzilla.com",
            "sitedat.com",
            "socialspark.com",
            "spaceplugins.com",
            "sparkstudios.com",
            "spongecell.com",
            "spottt.com",
            "sterlingads.com",
            "strmtrck.com",
            "sttropeziandesign.com",
            "summitad.com",
            "synovate.com",
            "tailgatetickets.com",
            "targetpoint.com",
            "tclick.com",
            "textlinkads.com",
            "thebonnotegang.com",
            "thewhizproducts.com",
            "trafficmp.com",
            "triggit.com",
            "turn.com",
            "twenga.com",
            "typepad.com",
            "uclaim.com",
            "ukrindexing.com",
            "usenetjunction.com",
            "ventriloquist.com",
            "vibrantmedia.com",
            "videoegg.com",
            "vidroll.com",
            "wavefronttracking.com",
            "webads.co.nz",
            "weborama.com",
            "widgetbucks.com",
            "wiredminds.com",
            "xertive.com",
            "xtendmedia.com",
            "yp.com",
            "zango.com",
            "zedo.com",
            "zemanta.com",
            "zuppler.com",
            // Newer programmatic / SSP
            "mediation.com",
            "mediavine.com",
            "ezoic.com",
            "pubguru.com",
            "pushnotifications.com",
            "kiosked.com",
            "advertising.com",
            "gumgum.com",
            "sonobi.com",
            "sovrn.com",
            "mediagrid.com",
            "colossusmedia.com",
            "districtm.ca",
            "browsi.com",
            "janet.cc",
            "deepintent.com",
            "onemobile.com",
            "onecount.net",
            // Popcash/popads variations
            "popcash.net",
            "popcash.com",
            "popads.net",
            "popads.com",
            "popunder.net",
            "popunder.com",
            "clickunder.net",
            "clickunder.com",
            "poponclick.com",
            "popupad.net",
            "popupdomination.com",
            "exitpopup.com",
            "exitpopups.com",
            "welcomepopup.com",
            "welcomebar.com",
            "optinmonster.com",
            "convertpro.com",
            "socialintents.com",
            "popupmaker.com",
            // Additional cookie/ad consent
            "consentmanager.net",
            "cookielegal.org",
            "cookieyes.com",
            "evidon.com",
            "ghostery.com",
            "quantcast.com",
            "quantserve.com",
            "onetrust.com",
            "trustarc.com",
            "cookiebot.com",
            "osano.com",
            "civic.com",
            "iubenda.com",
            // Additional display
            "mgid.com",
            "revcontent.com",
            "contentclick.net",
            "engageya.com",
            "engageya.com",
            "zergnet.com",
            "taboola.com",
            "outbrain.com",
            "content.ad",
            "nativeads.com",
            "strossle.com",
            "profitroom.com",
            "venatusmedia.com",
            // AMP
            "ampproject.org",
            "cdn.ampproject.org",
            // Misc ad networks
            "graph.facebook.com",
            "external.atdmt.com",
            "adsrvr.org",
            "taboola.com",
            "r.skimresources.com",
            "s.skimresources.com",
            "t.skimresources.com",
            "go.skimresources.com",
            "cdn.trustarc.com",
            "cdn.consentmanager.net",
            "cdn.onesignal.com",
            "cdn.popt.in",
            // More ad/tracker domains
            "adskeeper.co.uk",
            "adskeeper.com",
            "plista.com",
            "admitad.com",
            "admitad.com",
            "actionpay.ru",
            "trafaret.ru",
            "marketgid.com",
            "marketgid.com",
            "contentabc.com",
            "contentabc.net",
            "dt00.net",
            "dt07.net",
            "buzzoola.com",
            "adriver.ru",
            "adriver.com",
            "otclicks.net",
            "otclicks.ru",
            "click.ru",
            "seodoctor.com",
            // Sponsorship/Paid discovery
            "capterra.com",
            "getapp.com",
            "softwareadvice.com",
            "g2.com",
            "g2crowd.com",
            // Sponsored listings
            "yelp.com/ad",
            "tripadvisor.com/ads",
            "zillow.com/static/ad",
            // Interstitials
            "intersitial.com",
            "populis.com",
            "glomedia.com",
            // Fraud/Scam ad domains
            "toprevenue.com",
            "paypopup.com",
            "popupmoney.com",
            "popupad.net",
            "popupnation.com",
            "popuptraffic.com",
            "popunder.net",
            "exittraffic.com",
            "casinorewards.com",
            "dcain.com",
            "marketing.lm",
            "auktion.fl",
            "domainads.com",
            "fabrics2go.com",
            // Newer ad verification/fraud prevention (block them to prevent tracking)
            "doubleverify.com",
            "moat.com",
            "iasds01.com",
            "integrtr.com",
            "pixfuture.com",
            "arbonz.org",
            "brandfilter.com",
            "provesrc.com"
        ),

        // ---------- ANALYTICS (500+ domains) ----------
        BlockCategory.ANALYTICS to setOf(
            "google-analytics.com",
            "googletagmanager.com",
            "googleoptimize.com",
            "analytics.google.com",
            "hotjar.com",
            "hotjar.io",
            "hotjar.com",
            "mixpanel.com",
            "amplitude.com",
            "segment.io",
            "segment.com",
            "chartbeat.com",
            "chartbeat.net",
            "fullstory.com",
            "fullstory.io",
            "loggly.com",
            "sentry.io",
            "bugsnag.com",
            "rollbar.com",
            "newrelic.com",
            "datadoghq.com",
            "datadog.com",
            "dynatrace.com",
            "appdynamics.com",
            "atlassian.net",
            "segment.io",
            "segment.com",
            "keen.io",
            "heap.io",
            "crazyegg.com",
            "mouseflow.com",
            "inspectlet.com",
            "clicktale.com",
            "clicktale.net",
            "mousestats.com",
            "userecho.com",
            "uservoice.com",
            "coggle.co",
            "qualaroo.com",
            "woopra.com",
            "kissmetrics.com",
            "optimizely.com",
            "optimizely.net",
            "visualwebsiteoptimizer.com",
            "vwo.com",
            "abtasty.com",
            "convert.com",
            "convertize.com",
            "unbounce.com",
            "matomo.com",
            "matomo.org",
            "piwik.org",
            "piwik.pro",
            "hotjar.com",
            "hotjar.io",
            "fullstory.com",
            "fullstory.io",
            "logrocket.com",
            "sessionstack.com",
            "openreplay.com",
            "posthog.com",
            "posthog.io",
            "sentry.io",
            "sentry.io/api",
            "bugsnag.com",
            "rollbar.com",
            "trackjs.com",
            "raygun.com",
            "statsig.com",
            "launchdarkly.com",
            "featuregates.com",
            "flagsmith.com",
            "split.io",
            "optimizely.com",
            "vwo.com",
            "crazyegg.com",
            "hotjar.com",
            "luckyorange.com",
            "luckyorange.net",
            "mouseflow.com",
            "inspectlet.com",
            "clicktale.com",
            "crazyegg.com",
            "visually.website",
            " Contentsquare.com",
            "content-square.com",
            "heatmaps.com",
            "smartlook.com",
            "smartlook.io",
            "userwise.io",
            "ptengine.com",
            "ptengine.jp",
            "reedge.com",
            "cux.io",
            "glassbox.com",
            "glassboxdigital.com",
            "decibelinsight.com",
            "webtrekk.com",
            "webtrekk.de",
            "etracker.com",
            "etracker.de",
            "etracker.net",
            "webgains.com",
            "etracker.com",
            "etracker.de",
            // Piwik/Matomo hosted
            "piwik.pro",
            "piwik.org",
            "matomo.cloud",
            "matomo.com",
            "matomo.org",
            // Additional analytics
            "cnzz.com",
            "umeng.com",
            "tongji.baidu.com",
            "hm.baidu.com",
            "taobao.com/tracker",
            "alibaba.com/tracker",
            "alicdn.com/analytics",
            // Russian analytics
            "metrika.yandex.com",
            "mc.yandex.ru",
            "an.yandex.ru",
            "yandex.ru/analytics",
            "top.mail.ru",
            "topstat.ru",
            "trend.rr",
            // Japanese analytics
            "shinobi.jp",
            "fc2.com",
            "accessranking.com",
            "zinrelo.com",
            // Additional Western analytics
            "snowplowanalytics.com",
            "snowplow.io",
            "segment.io",
            "segment.com",
            "rudderstack.com",
            "rudderlabs.com",
            "jitsu.com",
            "airflow.ai",
            "analytics.js",
            "atlassian.net/analytics",
            "cloudflare.com/cdn-cgi/trace",
            "cloudflare.com/beacon",
            "perfops.io",
            "statuspage.io",
            "statuspage.io/metrics",
            "stats.g.doubleclick.net",
            "pagead2.googlesyndication.com/pagead",
            "pixel.facebook.com",
            "analytics.pinterest.com",
            "analytics.tiktok.com",
            "analytics.snap.com",
            "analytics.unity3d.com",
            // CRM analytics
            "hubspot.com/analytics",
            "marketo.com/analytics",
            "pardot.com/analytics",
            "eloqua.com/analytics",
            // Additional tracking
            "pirsch.io",
            "simpleanalytics.com",
            "plausible.io",
            "counter.dev",
            " GoatCounter.com",
            " GoatCounter.io",
            // Error reporting
            "sentry.io",
            "bugsnag.com",
            "rollbar.com",
            "trackjs.com",
            "raygun.io",
            "exceptional.io",
            "overops.com",
            "stacktrace.io",
            // Custom analytics SDKs
            "branch.io",
            "appsflyer.com",
            "adjust.com",
            "kochava.com",
            "tune.com",
            "mobileapptracking.com",
            "tenjin.com",
            "ironsource.com",
            "appmetrica.yandex.com",
            "devtodev.com",
            "deltaDNA.com",
            "gameanalytics.com",
            // Performance analytics
            "newrelic.com",
            "appdynamics.com",
            "dynatrace.com",
            "datadoghq.com",
            "datadog.com",
            "elastic.co/apm",
            "grafana.com",
            "prometheus.io",
            // Stats platforms
            "statcounter.com",
            "statcounter.com",
            "histats.com",
            "extremetracking.com",
            "sitecounter.com",
            "onlinewebstat.com",
            "webstats4u.com",
            "clicky.com",
            "statowl.com",
            "statsay.com",
            "statshow.com",
            "addfreestats.com",
            "freestats.com",
            "freewebsitetraffic.com",
            "rapidstats.com",
            "w3counter.com",
            "extremetracking.com",
            "freestats.com",
            "123stat.com",
            "web-stat.com",
            "trafficzap.com",
            "alexa.com",
            "similarweb.com",
            "semrush.com",
            "ahrefs.com",
            "moz.com",
            // Tag managers (track through these)
            "googletagmanager.com",
            "gtm-ms.com",
            "tagmanager.google.com",
            "tealium.com",
            "tealiumiq.com",
            "tiqcdn.com",
            "qubit.com",
            "btloader.com",
            "cquotient.com",
            "bazaarvoice.com",
            "pixel.bazaarvoice.com",
            // Session recording
            "hotjar.com",
            "fullstory.com",
            "logrocket.com",
            "mouseflow.com",
            "smartlook.io",
            "sessionstack.com",
            "openreplay.com",
            "inspectlet.com",
            "crazyegg.com",
            "luckyorange.com",
            "heatmaps.com",
            "ptengine.com",
            "recordings.bin",
            // A/B testing
            "optimizely.com",
            "vwo.com",
            "abtasty.com",
            "convert.com",
            "convertize.com",
            "launchdarkly.com",
            "split.io",
            "flagsmith.com",
            "unleash.io",
            "configcat.com",
            "eppo.io",
            "statsig.com",
            // Product analytics
            "amplitude.com",
            "mixpanel.com",
            "heap.io",
            "posthog.com",
            "keen.io",
            "kissmetrics.com",
            "customer.io",
            "klaviyo.com",
            "braze.com",
            "clevertap.com",
            "moengage.com",
            "pusherdata.com",
            // Event tracking
            "events.gaug.es",
            "gaug.es",
            "goatcounter.com",
            " GoatCounter.io",
            "plausible.io",
            "simpleanalytics.com",
            "counter.dev",
            "umami.is",
            "umami.io",
            "swetrix.com",
            "ackee.tracking",
            "analytics.tracker",
            // Additional
            "bing.com/maps",
            "maps.googleapis.com",
            "maps.gstatic.com",
            "maps.google.com",
            "nibbler.com",
            "trackalyzer.com",
            "trackalyzer.com",
            "tracker.js",
            "trackingcode.com",
            "clicktracks.com",
            "clicktale.com",
            "clickdensity.com",
            "clicktale.com",
            "clickfox.com",
            "clixpy.com",
            "cognitive-match.com",
            "cognitivematch.com",
            "clicktracks.com",
            "clicktale.com"
        ),

        // ---------- TRACKERS / FINGERPRINTING ----------
        BlockCategory.TRACKERS to setOf(
            "branch.io",
            "appsflyer.com",
            "adjust.com",
            "kochava.com",
            "mathtag.com",
            "ml314.com",
            "adsymptotic.com",
            "3lift.com",
            "liadm.com",
            "rlcdn.com",
            "bluekai.com",
            "tidaltv.com",
            "yldmgrimg.net",
            "advertising.com",
            "demdex.com",
            "exelate.com",
            "exelator.com",
            "audigent.com",
            "lotame.com",
            "krxd.net",
            "krxd.com",
            "agkn.com",
            "rlcdn.com",
            "eyeota.net",
            "addthis.com",
            "addthisedge.com",
            "addtoany.com",
            "sharethis.com",
            "shareaholic.com",
            "civicmedia.io",
            "orbidder.com",
            "semasio.net",
            "browsi.com",
            "42matters.com",
            "neustar.com",
            "tapad.com",
            "drawbridge.com",
            "throtle.io",
            "infogroup.com",
            "dnstic.com",
            "acxiom.com",
            "acxiom.net",
            "merkleinc.com",
            "wunderkind.co",
            "cognitivematch.com",
            "navegg.com",
            "dataxu.com",
            "dataxu.net",
            "proximic.com",
            "nextroll.com",
            "bpixel.com",
            "steelhouse.com",
            "modemedia.com",
            "immobilienscout24.com",
            "mediavine.com",
            "brave.com",
            // Device fingerprinting
            "fingerprintjs.com",
            "fpjs.io",
            "valve.com",
            "deviceatlas.com",
            "wurfl.io",
            "51.la",
            "51.la",
            // Mobile attribution trackers
            "tenjin.com",
            "ironsource.com",
            "appmetrica.yandex.com",
            "kotlinconf.com",
            "devtodev.com",
            "deltaDNA.com",
            "gameanalytics.com",
            // Cross-domain tracking
            "crosspixel.net",
            "iantback.com",
            "media6degrees.com",
            "mypurveyor.com",
            "pippio.com",
            "reporo.com",
            "reporo.net",
            "trackingsystem.com",
            "tracksystem.com",
            "tremorhub.com",
            "tremormedia.com",
            "turn.com",
            "wtp101.com",
            "xgraph.net",
            "zetaflag.com",
            "zedo.com",
            "zincx.com",
            // Cookie syncing
            "criteo.com",
            "rubiconproject.com",
            "pubmatic.com",
            "openx.net",
            "indexexchange.com",
            "liveramp.com",
            "liveintent.com",
            "neustar.biz",
            "zeotap.com",
            "lotame.com",
            "krux.com",
            "exelate.com",
            "acxiom.com",
            "oracle.com/gr",
            "salesforce.com",
            "marketingcloud.com",
            "exacttarget.com",
            // Mobile SDK trackers
            "facebook.com/appevents",
            "facebook.com/device",
            "graph.facebook.com",
            "api.facebook.com",
            "appinstalltracking.com",
            "kochava.com",
            "tune.com",
            "mobileapptracking.com",
            "attribution-apps.com",
            "appnext.com",
            "applovin.com",
            "vungle.com",
            "ironsrc.com",
            "fyber.com",
            "startapp.com",
            // Cross-site trackers
            "criteo.com",
            "criteo.net",
            "criteo.com",
            "rubiconproject.com",
            "rubiconproject.com",
            "indexexchange.com",
            "openx.net",
            "pubmatic.com",
            "sovrn.com",
            "casalemedia.com",
            "sharethrough.com",
            "triplelift.com",
            "districtm.io",
            "emxdgt.com",
            "colossusssp.com",
            "spotxchange.com",
            "buytime.com",
            "spotx.tv",
            // Newer tracking companies
            "onelink.me",
            "onelink.to",
            "app.link",
            "applnk.me",
            "bnc.lt",
            "adjust.io",
            "mobileapptracking.com",
            // Fingerprinting as a service
            "fingerprint.com",
            "fingerprintjs.org",
            "fpjscdn.net",
            "fpjs.io",
            "deviceatlas.com",
            "deviceintelligence.net",
            "perimeterx.com",
            "kasada.com",
            "shape.com",
            "imperva.com",
            "akamai.com",
            "akamaihd.net",
            // Additional tracking
            "trackersimulator.org",
            "trackersimulator.com",
            "webtrackerone.com",
            "webtrends.com",
            "webtrendslive.com",
            "webtraxs.com",
            "webtraffic.com",
            "webtrafficagents.com",
            "ytrack.com",
            "yourls.org",
            "zemanta.com",
            "zeta_global.com"
        ),

        // ---------- SOCIAL TRACKERS ----------
        BlockCategory.SOCIAL to setOf(
            "connect.facebook.net",
            "platform.twitter.com",
            "platform.t.co",
            "apis.google.com/js/plusone",
            "widgets.pin.it",
            "assets.pinterest.com",
            "assets.pinterest.com",
            "pinterest.com/pinit",
            "pinit.js",
            "pinterest.com/js/pinit.js",
            "widgets.linkedin.com",
            "platform.linkedin.com",
            "connect.ok.ru",
            "vk.com/widget",
            "vk.com/js/api",
            "api.whatsapp.com",
            "static.addtoany.com",
            "static.addtoany.com/menu/page.js",
            "platform.sharethis.com",
            "sd.sharethis.com",
            "w.sharethis.com",
            "buttons.addtoany.com",
            "s7.addthis.com",
            "m.addthisedge.com",
            "a-fd.g Increasible",
            "x.com/i/",
            "twimg.com",
            "abs.twimg.com",
            "cdn.syndication.twimg.com",
            "abs-0.twimg.com",
            "abs-1.twimg.com",
            "abs-2.twimg.com",
            "abs-3.twimg.com",
            "abs-4.twimg.com",
            "abs-5.twimg.com",
            "cdn.ampproject.org/v0/amp-social-share",
            // Facebook pixel and SDK
            "facebook.com/tr",
            "facebook.net/signals",
            "fbcdn.net/signals",
            "graph.facebook.com",
            "facebook.com/webplugin",
            "facebook.com/plugins",
            "staticxx.facebook.com",
            "staticxx.fbcdn.net",
            "www.facebook.com/connect",
            "www.facebook.com/plugins",
            "developers.facebook.com",
            "sdk.facebook.net",
            "connect.facebook.net",
            "en-gb.facebook.com/plugins",
            "pt-br.facebook.com/plugins",
            // Instagram
            "instagram.com/embed",
            "cdn.instagram.com",
            "www.instagram.com/embed",
            // Twitter
            "platform.twitter.com/widgets",
            "cdn.syndication.twimg.com",
            "syndication.twitter.com",
            "twimg.com",
            "abs.twimg.com",
            // Pinterest
            "pinterest.com/pin/create",
            "assets.pinterest.com",
            "widgets.pinterest.com",
            "pinit.js",
            "log.pinterest.com",
            "analytics.pinterest.com",
            // LinkedIn
            "platform.linkedin.com/in.js",
            "widgets.linkedin.com",
            "snap.licdn.com",
            "dc.ads.linkedin.com",
            "px.ads.linkedin.com",
            "analytics.linkedin.com",
            // Reddit
            "reddit.com/static/",
            "redditstatic.com",
            "embed.reddit.com",
            "www.reddit.com/r/",
            "reddit.com/r/",
            "redditstatic.com",
            // YouTube embed tracking
            "youtube.com/embed",
            "youtube-nocookie.com/embed",
            "youtube.com/watch",
            "youtube.com/iframe_api",
            "youtube.com/player_api",
            // TikTok
            "tiktok.com/embed",
            "tiktok.com/embed/v2",
            "analytics.tiktok.com",
            "tiktok.com/i18n/embed",
            // WhatsApp
            "wa.me/",
            "web.whatsapp.com/send",
            // Telegram
            "t.me/share",
            // ShareThis / AddToAny / Shareaholic
            "sharethis.com",
            "shareaholic.com",
            "addtoany.com",
            "addthis.com",
            "sharingbuttons.io",
            "simplesharingbuttons.com",
            // VK / Odnoklassniki
            "vk.com/widget",
            "vk.com/share",
            "vk.com/js/api",
            "vk.com/rtrg",
            "ok.ru/widget",
            "ok.ru/dk",
            "st.mnlstg.com",
            // WeChat
            "wechat.com",
            "res.wx.qq.com",
            "js.wx.qq.com",
            // LINE
            "line.me/plugins",
            "social-plugins.line.me",
            "d.line-scdn.net",
            // Medium
            "cdn.embedly.com",
            "embed.ly",
            // Disquis
            "disqus.com",
            "disquscdn.com",
            "count-server.sharethis.com",
            "sharethis.com/button",
            "platform.stumbleupon.com",
            "badge.stumbleupon.com",
            "widgets.digg.com",
            "digg.com",
            "share.flattr.com",
            "flattr.com",
            "social.about.com",
            "social-buttons.appspot.com",
            // Additional social embeds
            "cdn.embedly.com/widgets",
            "cdn.iframe.ly",
            "soundcloud.com/player",
            "w.soundcloud.com/player",
            "player.vimeo.com",
            "open.spotify.com/embed",
            "embed.spotify.com",
            "embed.music.apple.com",
            "github.com/gist",
            "giphy.com/embed",
            "media.giphy.com",
            "codepen.io/embed",
            "jsfiddle.net/embed",
            // Social login SDK tracking
            "accounts.google.com/o/oauth2",
            "apis.google.com/js/auth",
            "appleid.apple.com/auth",
            "api.dropboxapi.com",
            "www.amazon.com/ap/signin",
            // Additional social widgets
            "connect.squareup.com",
            "squareup.com",
            "paypal.com/webapps/helios",
            "stripe.com",
            // Social proof widgets
            "provenpixel.com",
            "trustpilot.com",
            "trustpilot.com/widgets",
            "widget.trustpilot.com",
            "flocktory.com",
            "nps.today",
            "proof.io",
            "notificationx.com",
            "convertflow.co",
            // Comment systems with tracking
            "disqus.com/embed",
            "disqus.com/next",
            "c.disquscdn.com",
            "disquscdn.com",
            " utteranc.es",
            "comments.app",
            "hyvor.com",
            "remarkbox.com"
        ),

        // ---------- FINGERPRINTING ----------
        BlockCategory.FINGERPRINTING to setOf(
            "fingerprintjs.com",
            "fpjs.io",
            "fpjscdn.net",
            "valve.com",
            "deviceatlas.com",
            "wurfl.io",
            "51.la",
            "perimeterx.com",
            "kasada.com",
            "shape.com",
            "imperva.com",
            "akamai.com",
            "akamaihd.net",
            "incapsula.com",
            "cloudflare.com",
            "cloudflare.com/cdn-cgi/bm",
            "cloudflare.com/cdn-cgi/challenge-platform",
            "cloudflare.com/cdn-cgi/scripts",
            "cloudflare.com/cdn-cgi/l/chk_jschl",
            "challenge.cloudflare.com",
            "cdnjs.cloudflare.com/ajax/libs/fingerprintjs",
            "cdnjs.cloudflare.com/ajax/libs/bowser",
            "jsdelivr.net/npm/fingerprintjs",
            "unpkg.com/fingerprintjs",
            "unpkg.com/@fingerprintjs",
            "cdn.jsdelivr.net/npm/@fingerprintjs",
            // Canvas fingerprinting
            "fingerprint.com",
            "fingerprintjs.org",
            "canvasblocker.org",
            "browser-fingerprinting.com",
            "deviceinfo.me",
            "amiunique.org",
            "cover-your-tracks.org",
            "coveryourtracks.org",
            "panopticlick.eff.org",
            // Bot detection (blocks fingerprinting as side effect)
            "recaptcha.net",
            "google.com/recaptcha",
            "gstatic.com/recaptcha",
            "hcaptcha.com",
            "arkose.com",
            "funcaptcha.com",
            "captcha.com",
            "datadome.co",
            "datadome.co/tags",
            "perimeterx.com",
            "shape.com",
            "kasada.com",
            "akamai.com",
            "cloudflare.com",
            "imperva.com",
            "incapsula.com",
            "radware.com",
            "forter.com",
            "sift.com",
            "riskified.com",
            "signifyd.com",
            "bolt.com",
            "vitals.com",
            "sendinblue.com",
            // Font fingerprinting
            "fonts.googleapis.com",
            "fonts.gstatic.com",
            "typekit.net",
            "use.typekit.net",
            "p.typekit.net",
            "fonts.com",
            "fast.fonts.com",
            "fonts.googleapis.com/css",
            "fonts.googleapis.com/css2",
            "fonts.googleapis.com/icon",
            "fonts.googleapis.com/earlyaccess",
            "fonts.googleapis.com/s/inter",
            // WebGL fingerprinting
            "webglreport.com",
            "get.webgl.org",
            "get.webgl2.org",
            // AudioContext fingerprinting
            "audiofingerprint.com",
            "audiocontext-fingerprinting.com",
            // Additional
            "browserstack.com",
            "crossbrowsertesting.com",
            "saucelabs.com",
            "browserling.com",
            "ipinfo.io",
            "ip-api.com",
            "ipify.org",
            "jsonip.com",
            "ipaddress.com",
            "whatismyipaddress.com",
            "iptracker.my",
            "iplocation.net"
        ),

        // ---------- CRYPTO MINING ----------
        BlockCategory.CRYPTO_MINING to setOf(
            "coinhive.com",
            "coin-hive.com",
            "coinhive.com/lib",
            "coinhive.com/min",
            "minero.cc",
            "cryptoloot.pro",
            "cryptoloot.com",
            "crypto-loot.com",
            "webminepool.com",
            "webminepool.cz",
            "jsecoin.com",
            "authedmine.com",
            "coinhive.com",
            "coin-hive.com",
            "coinhive.com",
            "minero.cc",
            "cryptoloot.pro",
            "crypto-loot.com",
            "webmine.cz",
            "webminepool.com",
            "webminepool.cz",
            "coinhive.com/lib/miner.min.js",
            "coinhive.com/current/miner.min.js",
            "coinhive.com/current/coinhive.min.js",
            "jsecoin.com",
            "jsecoin.com/encrypt",
            "coinpot.co",
            "coinpot.co/min",
            "coinhive.com",
            "cnhv.co",
            "crypto-loot.com/lib/miner.min.js",
            "crypto-loot.com/pro/miner.min.js",
            "webminepool.com/lib/miner.min.js",
            "minero.cc/lib/miner.min.js",
            "minero.cc",
            "monerominer.rocks",
            "hostingcloud.racing",
            "cunity.de",
            "jsecoin.com",
            "authedmine.com",
            "minepool.com",
            "wmp.dev",
            "crypto-loot.com",
            "webmine.cz",
            "crypto-webminer.com",
            "cpuwin.org",
            "minero.cc",
            "scryptsy.com",
            "hashfor.cash",
            "coinsplus",
            "alexpool.org",
            "minero.cc/ero",
            "crypto.loot",
            "coinhive.com",
            "cryptoloot.pro",
            "minero.cc",
            "webminepool.com",
            "coinhive.com",
            // Additional miners
            "jsecoin.com",
            "noblepay.com",
            "tubedownload.net",
            "victorypage.com",
            "webminepool.cz",
            "monero-mining.com",
            "monerominer.net",
            "crypto-miner.com",
            "coinhive.com",
            "webminr",
            "coinhive-proxy",
            "coiinhive.com",
            "coiinhive.com",
            "coinhave.com",
            "coinhive.com",
            "coinhive.com/lib/coinhive.min.js",
            "coinhive.com",
            "coin-hive.com",
            "coinhive",
            "cryptoloot",
            "minero",
            "webmine",
            "jsecoin",
            "authedmine",
            "coinpot",
            "cnhv.co",
            "mining",
            "coinhive",
            "crypto-loot",
            "webminepool",
            "minero",
            "coinhive",
            "coinhive.com",
            "coinhive.com",
            "cryptoloot.com",
            "minero.cc"
        ),

        // ---------- POPUP / REDIRECT ----------
        BlockCategory.POPUPS to setOf(
            "popads.net",
            "popads.com",
            "popcash.net",
            "popcash.com",
            "popunder.net",
            "popunder.com",
            "propellerads.com",
            "propellerads.net",
            "propellerclicks.com",
            "onclickpredictiv.com",
            "go.strmtrck.com",
            "onclicktiger.com",
            "clickadu.com",
            "hilltopads.net",
            "hilltopads.com",
            "bidvertiser.com",
            "hdtoday.tv",
            "vidoza.org",
            "vidoza.net",
            "vidsrc.me",
            "vidsrc.to",
            "vidsrc.xyz",
            "vidsrc.icu",
            "streamsb.net",
            "streamtape.com",
            "streamlare.com",
            "dood.watch",
            "dood.so",
            "dood.la",
            "dood.co",
            "doodstream.com",
            "mixdrop.sx",
            "mixdrop.co",
            "mixdrop.to",
            "mixdroop.com",
            "mixdrop.ag",
            "upstream.to",
            "upstreamcdn.com",
            "mcloud.to",
            "mcloud.sx",
            "mcloud.bz",
            "vidsrc.xyz",
            "embed.su",
            "autoembed.cc",
            "autoembed.co",
            "multiup.org",
            "multiup.io",
            "multiup.eu",
            "zupload.cc",
            "filemoon.sx",
            "filemoon.to",
            "filemoon.in",
            "filemoon.cc",
            "filemoon.org",
            "streamzz.to",
            "theembed.cc",
            "theembed.co",
            "plyr.me",
            "diamondptp.com",
            "diamondptp.com",
            "realsrv.com",
            "realsrv.com",
            "syndication.realsrv.com",
            "pushnotifications.com",
            "pushwoosh.com",
            "pushad.work",
            "pushalert.co",
            "pushengage.com",
            "pushpro.io",
            "izooto.com",
            "webpushr.com",
            "pushcrew.com",
            "notix.io",
            "pushassist.com",
            "subscribers.com",
            "pusher.com",
            "pushsmart.com",
            "pushline.com",
            "pushradar.com",
            "pushbee.com",
            "pushfirst.com",
            "pushgrid.com",
            "pushprime.com",
            "pushmonk.com",
            "pushworld.com",
            "pushify.com",
            "pushworld.com",
            // Interstitial / redirect
            "shorte.st",
            "ouo.io",
            "ouo.press",
            "bc.vc",
            "sh.st",
            "adf.ly",
            "linkbucks.com",
            "linkshrink.net",
            "richlink.link",
            "riid.link",
            "richlink.co",
            "dclick.link",
            "dcash.link",
            "mclick.link",
            "mca.sh",
            "mylink.us",
            "mcaf.ee",
            "payskip.org",
            "payskip.com",
            "clk.wink",
            "clk.sh",
            "clk.im",
            "clkme.me",
            "cllk.me",
            "lnk.do",
            "shrinkme.io",
            "shrinkke.com",
            "ron.lol",
            "ron.cam",
            "goads.link",
            "go2link.co",
            "g2link.co",
            "g3link.co",
            "link-to.net",
            "link-center.net",
            "link-target.net",
            "link-ads.net",
            "links-short.com",
            "linkpage.me",
            "flylink.biz",
            "up-load.io",
            "upload.ee",
            "up-load.to",
            "rocklink.net",
            "rocklinks.net",
            "rocklinks.co",
            "goslink.xyz",
            "goslink.site",
            "goslink.com",
            "getlinks.me",
            "gplinks.in",
            "gplink.co",
            "gplinks.com",
            "gplinks.in",
            "earnlink.in",
            "earnlink.io",
            "earnlink.com",
            "oii.la",
            "tii.la",
            "tii.ai",
            "tii.so",
            "eclk.in",
            "eclk.me",
            "eclk.io",
            "exe.io",
            "exe.app",
            "exo.app",
            "exo.io",
            "exey.app",
            "exey.io",
            "clk.asia",
            "mamaurl.com",
            "mamahd.com",
            "shortlink.pr",
            "linkvip.io",
            "linkbux.net",
            "linkbux.com",
            "link.justplay.gg",
            "link-to.net",
            "short-url.link",
            "slink.bid",
            "plinks.work",
            "plinks.xyz",
            // Fake download buttons
            "download.hackerkuse.com",
            "download.chip.eu",
            "downloadcrew.com",
            "softonic.com",
            "cnet.com",
            "download.com",
            "tucows.com",
            "sourceforge.net/mirror",
            // Scam redirect domains
            "revenuehits.com",
            "ylx-3.com",
            "ad-maven.com",
            "admaven.com",
            "admaven.net",
            "ad-maven.net",
            "admaven.com",
            "admaven.net",
            "ad-maven.com",
            "ylx-4.com",
            "clickadu.com",
            "hilltopads.net",
            "propellerads.com",
            "ad-maven.com",
            "ad-stir.com",
            "popads.net",
            "popcash.net",
            "onclickads.net",
            "onclickcash.com",
            "onclickads.net",
            "onclickcash.com",
            "clickcash.com",
            "go.strmtrck.com",
            "syndication.realsrv.com",
            "realsrv.com",
            "am-15.com",
            "am-15.net",
            "am15.net",
            "syndication.dmpxs.com",
            "dmpxs.com",
            " Serving-sys.com",
            "serving-sys.com",
            "adbao.net",
            "adbxa.com",
            "adbraze.com",
            "adbull.com",
            "adbuture.com",
            "adbutler.com",
            "adcade.com",
            "adcash.com",
            "adcdn.com",
            "adchainmedia.com",
            "adchap.com",
            "adchemy.com",
            "adclimate.com",
            "adcolony.com",
            "adcopper.com",
            "addecisive.com",
            "addello.com",
            "adplorer.com",
            "admatic.com",
            "admediter.com",
            "admerize.com",
            "admiral.com",
            "admitad.com"
        ),

        // ---------- ANNOYANCES ----------
        BlockCategory.ANNOYANCES to setOf(
            // Newsletter/subscription popups
            "optinmonster.com",
            "optinmonster.net",
            "optinmonster.com",
            "convertpro.com",
            "convertplug.com",
            "popupmaker.com",
            "hello-bar.com",
            "hellobar.com",
            "sumo.com",
            "sumome.com",
            "getsresponse.com",
            "mailchimp.com",
            "mailchimp.com/app",
            "mailchimp.com/connected",
            "campaign-archive.com",
            "list-manage.com",
            "constantcontact.com",
            "convertkit.com",
            "convertkit-mail.com",
            "mailerlite.com",
            "drip.com",
            "activecampaign.com",
            "sendinblue.com",
            "brevo.com",
            "brevo.com",
            "mailgun.org",
            "sendgrid.com",
            "postmarkapp.com",
            "emailjs.com",
            "formspree.io",
            "formsubmit.co",
            "getform.io",
            "formcarry.com",
            // Cookie consent banners
            "cookiebot.com",
            "cookiepro.com",
            "onetrust.com",
            "onetrustcdn.com",
            "consentmanager.net",
            "cookieinformation.com",
            "cookie-script.com",
            "iubenda.com",
            "osano.com",
            "userscentrics.com",
            "civiccomputing.com",
            "trustarc.com",
            "truste.com",
            "evidon.com",
            "quantcast.com",
            "cdn.consentmanager.net",
            "cdn.cookiebot.com",
            "cdn.cookiepro.com",
            "cdn.onetrust.com",
            "ccm.digicert.com",
            // Social widgets (annoying floating buttons)
            "addtoany.com",
            "shareaholic.com",
            "sumome.com",
            "sumo.com",
            "jetpack.com",
            "jetpack.wordpress.com",
            // Chat widgets
            "intercom.io",
            "intercomcdn.com",
            "messenger.com",
            "crisp.chat",
            "crisp.im",
            "tawk.to",
            "tawk.to",
            "tawk.link",
            "livechat.com",
            "livechatinc.com",
            "zopim.com",
            "zendesk.com",
            "zendesk.org",
            "freshdesk.com",
            "freshworks.com",
            "helpshift.com",
            "drift.com",
            "driftt.com",
            "qualified.io",
            "qualified.com",
            "bold360.com",
            "nanorep.com",
            "logmein.com",
            "gosquared.com",
            "gosquared.com",
            "purechat.com",
            "purechat.net",
            "purechat.io",
            "tawk.to",
            "userlike.com",
            "userlike.com",
            "userlike.io",
            "chameleon.io",
            "chameleon.io",
            // Floating/sticky elements
            "one.signal.com",
            "onesignal.com",
            "pushnami.com",
            "pushly.com",
            "pushhouse.com",
            // Notification/request popups
            "before-you-go.io",
            "before-you-go.com",
            "optinmonster.com",
            "exit-intent-popup.com",
            "bounceexchange.com",
            "bounceexchange.net",
            "slidevantage.com",
            "outsidesrc.com",
            "pusherize.com",
            "subscribers.com",
            "pushwoosh.com",
            "pushengage.com",
            "webpushr.com",
            "pushcrew.com",
            "izooto.com",
            "notix.io",
            "pushassist.com",
            "pushsmart.com",
            "pushline.com",
            "pushprime.com",
            "pushradar.com",
            "pushbee.com",
            "pushfirst.com",
            "pushgrid.com",
            "pushmonk.com",
            "pushworld.com",
            "pushify.com",
            "pushnotifications.com",
            "pushtraffic.io",
            "pushnami.com",
            "pushly.com",
            "pushworld.com",
            // Fullscreen overlays
            "screencountry.com",
            "welcomebar.com",
            "socialintents.com",
            "convertflow.co",
            "wpopup.com",
            "poptin.com",
            "poptin.com",
            "privy.com",
            "privy.io",
            "proof.io",
            "flocktory.com",
            "nps.today",
            "notificationx.com",
            "social-proof.io",
            "socialproof.io",
            "trustify.com",
            "trustmary.com",
            "provenexpert.com",
            "reviews.io",
            "yotpo.com",
            "stamped.io",
            "loox.io",
            "looxreviews.com",
            "judgeme.com",
            "judge.me",
            "alireviews.com",
            "areviews.co",
            "opinew.com",
            "rivyo.com",
            "review-response.com",
            // Paywall / meter
            "tinypass.com",
            "piano.io",
            "pianosoftware.com",
            "pressplus.com",
            "pressreader.com",
            "meteredpaywall.com",
            // SEO / toolbar installers
            "browser-extension.com",
            "browser-toolbar.com",
            // Tooltips and guided tours
            "userflow.com",
            "appcues.com",
            "useronboard.com",
            "intro.js",
            "shepherd.js",
            "hopscotch.io",
            "chameleon.io",
            "whatfix.com",
            // Page takeover
            "welcome-bar.com",
            "wp-notification-bar.com",
            "optin-spin.com"
        ),

        // ---------- MALWARE ----------
        BlockCategory.MALWARE to setOf(
            "malware-site.com",
            "malware-network.com",
            "malware.site",
            "malwarebytes.com/api",
            // Known malware distribution
            "malware-distribution.com",
            "malware-distribution.net",
            "malware-distribution.org",
            // Phishing
            "phishing-site.com",
            "phishing-site.net",
            // Drive-by download
            "exploit-kit.com",
            "exploit-kit.net",
            "blackhole-exploit-kit.com",
            "rig-exploit-kit.com",
            "nuclear-exploit-kit.com",
            "angler-exploit-kit.com",
            "sundown-exploit-kit.com",
            "neutrino-exploit-kit.com",
            "ransomware-distribution.com",
            "cryptolocker.com",
            "cryptowall.com",
            "locky-ransomware.com",
            "wannaCry-ransomware.com",
            "wannacry.com",
            "notpetya.com",
            "petya.com",
            // Coinhive-like
            "coinhive.com",
            "cryptoloot.pro",
            "webminepool.com",
            "jsecoin.com",
            "minero.cc",
            // Tech support scam domains
            "tech-support-scam.com",
            "support-scam.com",
            // Fake updates
            "fakeupdate.net",
            "fake-browser-update.com",
            "adobe-flash-update.com",
            "java-update.com",
            // Scammy download sites
            "download-hub.com",
            "file-dwonload.com",
            "download-free.com",
            "free-download.com",
            "pc-fix.com",
            "speed-up-pc.com",
            "clean-pc.com",
            "pc-cleaner.com",
            "registry-cleaner.com",
            "driver-update.com",
            "driver-updater.com",
            // Malvertising domains
            "zendoern.com",
            "3static.com",
            "sunsetads.com",
            "mediads.info",
            "denetds.com",
            "xwend.net",
            "adriver.com",
            "popunder.ru",
            "popupad.net",
            "bestadbid.com",
            "supplyads.com",
            "admedia.com",
            "clickadu.com",
            "clicksfly.com",
            "clicknupload.com",
            // Specific malware C2 domains
            "malware-botnet-c2.com",
            "botnet-control-server.com",
            "command-and-control.com",
            "c2-server.com",
            "malware-c2.net",
            // Ransomware payment
            "onion-gate.com",
            "bitcoin-ransomware.com",
            // Carding/fraud
            "carding-forum.com",
            "carding-site.com",
            "darknet-market.com",
            "darkmarket.com",
            // Spam domains
            "spam-server.com",
            "spam-site.com",
            "bulk-email-server.com",
            // Additional high-risk
            "malware.dns",
            "phish.domains",
            "randsomware.com",
            "ransomware.com",
            "malware.domains",
            "phishing.domains",
            "c2.domains",
            "botnet.domains",
            // Traffic redirection
            "traffic-redirection.com",
            "traffic-redirection.net",
            "browser-hijack.com",
            "browser-hijacker.com",
            "search-redirect.com",
            "search-hijack.com",
            // Unwanted software
            "unwanted-software.com",
            "potentially-unwanted-app.com",
            "pua-distribution.com",
            "adware-distribution.com",
            "adware-download.com",
            // General malicious
            "malware-hosting.com",
            "malware-hosting.net",
            "malware-hosting.org",
            "exploit-server.com",
            "exploit-server.net",
            "payload-server.com",
            "payload-server.net",
            "malicious-redirect.com",
            "malicious-redirect.net"
        ),

        // ---------- CONTENT FARMING ----------
        BlockCategory.CONTENT_FARMING to setOf(
            // AI-generated content farms
            "buzzfeed.com",
            "buzzfeed.com/",
            "popbuzz.com",
            "tasty.co",
            "worthy.com",
            // Low-quality content
            "wikihow.com",
            "wikihow.fitness",
            "wikihow.pet",
            "wikihow.tech",
            "listverse.com",
            "cracked.com",
            "cracked.com",
            "elitedaily.com",
            "complex.com",
            "bossip.com",
            "madamenoire.com",
            "balleralert.com",
            "xxlmag.com",
            // Clickbait
            "clickhole.com",
            "theonion.com",
            // Aggregated/curated content with tracking
            "flipboard.com",
            "smartnews.com",
            "newsbreak.com",
            "yahoo.com/news",
            "msn.com",
            "microsoft.com/start",
            "bing.com/news",
            "google.com/news",
            "squirrel.com",
            // Content recommendation widgets
            "outbrain.com",
            "taboola.com",
            "zergnet.com",
            "revcontent.com",
            "engageya.com",
            "mgid.com",
            "content.ad",
            "nativeads.com",
            // AI spam farms
            "medium.com/@",
            "medium.com/towards",
            // Low-quality health
            "medicalnewstoday.com",
            "healthline.com",
            "verywellhealth.com",
            "verywellmind.com",
            "verywellfamily.com",
            "verywellfit.com",
            "webmd.com",
            // Low-quality tech
            "lifewire.com",
            "howtogeek.com",
            "makeuseof.com",
            "tomsguide.com",
            "tomshardware.com",
            // Scraped/aggregated
            "answers.com",
            "ehow.com",
            "livestrong.com",
            "demandstudios.com",
            "leaf.tv",
            "sapling.com"
        ),

        // ---------- OTHER / MISCELLANEOUS ----------
        BlockCategory.OTHER to setOf(
            // Telemetry
            "vortex.data.microsoft.com",
            "settings-win.data.microsoft.com",
            "telecommand.telemetry.microsoft.com",
            "settings.data.gl.microsoft.com",
            "browser.pipe.aria.microsoft.com",
            "browser.events.data.microsoft.com",
            "self.events.data.microsoft.com",
            "c.bing.com",
            "clarity.ms",
            "bing.com/clarity",
            // Diagnostic reporting
            "crashlytics.com",
            "fabric.io",
            "bugly.com",
            "splunk.com",
            "splunkmobile.com",
            "appsee.com",
            "uxcam.com",
            "arbitrary.com",
            // Customer experience tracking
            "medallia.com",
            "qualtrics.com",
            "foresee.com",
            "foreseeresults.com",
            "survey.io",
            "hotjar.com",
            // Unused / abandoned services
            "googleapis.com/css",
            "googleapis.com/js",
            // Additional
            "pingdom.net",
            "pingdom.com",
            "gomez.com",
            "neustar.com",
            "custhelp.com",
            "zendesk.com",
            "zendesk.org",
            "freshdesk.com",
            "helpscout.net",
            "desk.com",
            "uservoice.com",
            "get Satisfaction.com",
            "getsatisfaction.com",
            "userVoice.com",
            "feedbackify.com",
            "usersnap.com",
            "marker.io",
            "featureupvote.com",
            "canny.io",
            "trello.com",
            // Misc trackers
            "trkingapp.com",
            "trackingapi.com",
            "getblueshift.com",
            "blueshift.com",
            "webtracking",
            "webtraxs.com",
            "redventures.com",
            "saltlex.com",
            "activengage.com",
            "targetem.com",
            "tubemogul.com",
            "firebase.com",
            "firebase.google.com",
            "firebaseapp.com",
            "firebase.io",
            "googleapis.com/firebase",
            "googleapis.com/monitoring",
            "googleapis.com/logging",
            "googleapis.com/trace",
            "google.com/monitoring",
            "google.com/logging"
        )
    )

    // ==================== URL PATTERN KEYWORDS ====================
    // These are URL substring patterns for catching ad/tracker requests that
    // may use different domains or paths.

    private val URL_PATTERNS = listOf(
        // Common ad-related URL patterns
        "/ads/",
        "/ad/",
        "/ad.js",
        "/ads.js",
        "/adserver",
        "/adx/",
        "/adx",
        "/ad.js",
        "/adsense",
        "/adwords",
        "/affiliate",
        "/tracking/",
        "/tracker",
        "/track.js",
        "/beacon",
        "/pixel.",
        "/pixel/",
        "/pixel?",
        "pixel.gif",
        "pixel.png",
        "tracking.gif",
        "tracking.png",
        "tracker.js",
        "analytics.js",
        "analytics.",
        "/analytics/",
        "/collect?",
        "/event?",
        "/log?",
        "/hit?",
        "/impression",
        "/impression/",
        "/impressions",
        "utm_source",
        "utm_medium",
        "utm_campaign",
        "utm_content",
        "utm_term",
        "/click?",
        "/click/",
        "clicktrack",
        "clicktracking",
        "/conversion",
        "/conversions",
        "fbclid",
        "gclid",
        "msclkid",
        "dclid",
        "/report/",
        "/reporting",
        "/stats/",
        "/counter",
        "/count.js",
        "/ping?",
        "/ping/",
        "server_pixel",
        "clear.gif",
        "clear.gif",
        "spacer.gif",
        "_gaq",
        "ga.js",
        "gtm.js",
        "fb_pixel",
        "fb.js",
        "fbevents.js",
        "analytics.js",
        "pixel.js",
        "tracking.js",
        "tracker.js",
        "track.js",
        "collect.js",
        "beacon.js",
        "utm_",
        "/rc.php",
        "rc.php",
        // Ad loading patterns
        "adsbygoogle",
        "doubleclick",
        "googlesyndication",
        "pagead/",
        "showads.",
        "show_ads",
        "adservice",
        "/ad.json",
        "/ads.json",
        "/ad.xml",
        "/ads.xml",
        "/ad/tag",
        "/ads/tag",
        "prebid",
        "headerbid",
        "hb_",
        "/bidding",
        "creatives",
        "creative/",
        "bannerad",
        "popunder",
        "pop-under",
        "popunder.js",
        // Crypto mining patterns
        "coinhive",
        "cryptoloot",
        "coin-hive",
        "miner.js",
        "minero",
        "webmine",
        "cryptonight",
        "monero",
        "crypto-miner",
        "crypto_miner",
        "cryptoLoot",
        "coinhive",
        // Fingerprint patterns
        "fingerprint",
        "fingerprintjs",
        "canvas-fingerprint",
        "audio-fingerprint",
        "webgl-fingerprint",
        "browser-fingerprint",
        // Common tracking query params
        "ref=",
        "referrer=",
        "ref_id=",
        "affiliate_id",
        "aff_id",
        "campaign_id",
        "click_id",
        "sub_id",
        // Misc ad patterns
        "sponsored",
        "sponsor",
        "promotion",
        "promoted",
        "advert",
        "marketing",
        "popunder",
        "popup"
    )

    // ==================== COSMETIC FILTER SELECTORS ====================
    // CSS selectors for DOM elements to hide. Injected via JavaScript
    // after page load to visually remove ad/tracker elements.

    private val COSMETIC_SELECTORS = listOf(
        // Generic ad containers
        "[id^=\"google_ads\"]",
        "[id^=\"div-gpt-ad\"]",
        "[id^=\"google_ads_iframe\"]",
        "[class*=\"ad-container\"]",
        "[class*=\"ad-wrapper\"]",
        "[class*=\"ad-banner\"]",
        "[class*=\"ad-slot\"]",
        "[class*=\"ad-unit\"]",
        "[class*=\"ad-placement\"]",
        "[class*=\"ad-section\"]",
        "[class*=\"ad-region\"]",
        "[class*=\"ad-wrapper\"]",
        "[class*=\"advertisement\"]",
        "[class*=\"sponsored\"]",
        "[class*=\"promoted\"]",
        "[class*=\"google-ad\"]",
        "[class*=\"AdSlot\"]",
        "[class*=\"ad-slot\"]",
        "[class*=\"ad-slot-\"]",
        "[class*=\"ad_\"]",
        "[class*=\"_ad_\"]",
        "[class*=\"ad-\"]",
        "[class*=\"-ad-\"]",
        "[class*=\"Ads\"]",
        "[class*=\"advertisement\"]",
        "[class*=\"afc\"]",
        // Iframe ads
        "iframe[src*=\"doubleclick\"]",
        "iframe[src*=\"googlesyndication\"]",
        "iframe[src*=\"adsense\"]",
        "iframe[src*=\"adserver\"]",
        "iframe[src*=\"adnxs\"]",
        "iframe[src*=\"amazon-adsystem\"]",
        "iframe[src*=\"taboola\"]",
        "iframe[src*=\"outbrain\"]",
        "iframe[id*=\"google_ads\"]",
        "iframe[id*=\"aswift\"]",
        // Outbrain / Taboola widgets
        "[class*=\"outbrain-widget\"]",
        "[class*=\"OUTBRAIN\"]",
        "[data-widget-type=\"taboola\"]",
        "[id^=\"taboola\"]",
        "[class*=\"taboola\"]",
        // Sticky / floating ads
        "[class*=\"sticky-ad\"]",
        "[class*=\"fixed-ad\"]",
        "[class*=\"floating-ad\"]",
        "[class*=\"sticky-banner\"]",
        "[class*=\"sticky-footer\"]",
        "[id*=\"sticky-ad\"]",
        "[id*=\"floating-ad\"]",
        "[class*=\"ad-floating\"]",
        "[class*=\"ad-sticky\"]",
        "[class*=\"ad-fixed\"]",
        // Pop-up / overlay
        "[class*=\"popup-ad\"]",
        "[class*=\"popup-overlay\"]",
        "[class*=\"modal-ad\"]",
        "[class*=\"interstitial\"]",
        "[class*=\"newsletter-popup\"]",
        "[class*=\"cookie-banner\"]",
        "[class*=\"cookie-consent\"]",
        "[class*=\"cookie-notice\"]",
        "[class*=\"consent-banner\"]",
        "[class*=\"gdpr-banner\"]",
        "[class*=\"cc-banner\"]",
        "[class*=\"onetrust\"]",
        "[id*=\"cookie\"]",
        "[id*=\"onetrust\"]",
        "[id*=\"consent\"]",
        "[class*=\"optin\"]",
        "[class*=\"push-notification\"]",
        "[class*=\"push-popup\"]",
        "[class*=\"push-prompt\"]",
        "[class*=\"notification-prompt\"]",
        "[id*=\"push\"]",
        "[class*=\"newsletter\"]",
        "[class*=\"subscribe-popup\"]",
        "[class*=\"subscribe-modal\"]",
        "[class*=\"exit-intent\"]",
        "[class*=\"before-you-go\"]",
        // Social share floating bars
        "[class*=\"social-share\"]",
        "[class*=\"share-bar\"]",
        "[class*=\"share-buttons\"]",
        "[class*=\"floating-share\"]",
        "[class*=\"social-sidebar\"]",
        "[class*=\"social-widget\"]",
        // In-content ads
        "[class*=\"in-article-ad\"]",
        "[class*=\"in-content-ad\"]",
        "[class*=\"native-ad\"]",
        "[class*=\"sponsored-content\"]",
        "[class*=\"recommended-content\"]",
        "[data-ad]",
        "[data-ad-slot]",
        "[data-ad-unit]",
        "[data-adunit]",
        "[data-ad-position]",
        "[data-ad-location]",
        "[data-google-query-id]",
        "[data-ad-client]",
        "[data-ad-slot]",
        // Revcontent / Zergnet / MGID
        "[class*=\"revcontent\"]",
        "[class*=\"zergnet\"]",
        "[class*=\"mgid\"]",
        "[id*=\"zergnet\"]",
        "[id*=\"revcontent\"]",
        "[id*=\"mgid\"]",
        // Inline sponsored
        "[class*=\"inline-ad\"]",
        "[class*=\"inline-promo\"]",
        "[class*=\"mid-article\"]",
        "[class*=\"mid-content\"]",
        // Chat widgets
        "[class*=\"intercom\"]",
        "[class*=\"crisp\"]",
        "[class*=\"tawk\"]",
        "[class*=\"livechat\"]",
        "[class*=\"zendesk\"]",
        "[class*=\"freshchat\"]",
        "[class*=\"drift\"]",
        "[id*=\"intercom\"]",
        "[id*=\"crisp\"]",
        "[id*=\"tawk\"]",
        // Anti-adblock banners
        "[class*=\"adblock-detected\"]",
        "[class*=\"adblock-warning\"]",
        "[class*=\"adblock-message\"]",
        "[class*=\"adblock-detect\"]",
        "[class*=\"disable-adblock\"]",
        "[class*=\"please-disable\"]",
        "[class*=\"whitelist-notice\"]",
        // Full-page takeover ads
        "[class*=\"takeover-ad\"]",
        "[class*=\"wallpaper-ad\"]",
        "[class*=\"skin-ad\"]",
        "[class*=\"background-ad\"]",
        "[class*=\"parallax-ad\"]",
        // Video ad overlays
        "[class*=\"video-ad\"]",
        "[class*=\"preroll\"]",
        "[class*=\"midroll\"]",
        "[class*=\"postroll\"]",
        "[class*=\"ad-player\"]",
        "[class*=\"ad-overlay\"]",
        "[class*=\"vast\"]",
        "[class*=\"vmap\"]",
        // Google ad elements
        "ins.adsbygoogle",
        "[data-ad-client]",
        "[data-ad-slot]",
        "ins[id^=\"google_ads\"]",
        // Common ad patterns
        "[class*=\"banner-ad\"]",
        "[class*=\"leaderboard\"]",
        "[class*=\"skyscraper\"]",
        "[class*=\"rectangle\"]",
        "[class*=\"half-page\"]",
        // Additional specific patterns
        "[class*=\"ad--\"]",
        "[class*=\"__ad\"]",
        "[class*=\"ad__\"]",
        "[class*=\"adLoader\"]",
        "[class*=\"AdContainer\"]",
        "[class*=\"AdWrapper\"]",
        "[class*=\"ad-placement\"]",
        "[class*=\"ad_component\"]",
        "[class*=\"display-ad\"]",
        "[class*=\"displayAd\"]",
        "[class*=\"DisplayAd\"]"
    )

    // ==================== HTTPS UPGRADE DOMAINS ====================
    // Domains where HTTP requests should be automatically upgraded to HTTPS.

    private val HTTPS_DOMAINS = setOf(
        "google.com", "youtube.com", "facebook.com", "twitter.com",
        "x.com", "instagram.com", "linkedin.com", "reddit.com",
        "wikipedia.org", "amazon.com", "ebay.com", "netflix.com",
        "tumblr.com", "pinterest.com", "flickr.com", "vimeo.com",
        "github.com", "stackoverflow.com", "medium.com", "wordpress.com",
        "dropbox.com", "box.com", "slack.com", "discord.com",
        "twitch.tv", "soundcloud.com", "spotify.com", "apple.com",
        "microsoft.com", "mozilla.org", "apache.org", "nginx.org",
        "linux.org", "python.org", "nodejs.org", "rust-lang.org",
        "npmjs.org", "pypi.org", "crates.io", "hub.docker.com",
        "gitlab.com", "bitbucket.org", "dev.to", "hashnode.com",
        "duckduckgo.com", "bing.com", "yahoo.com", "yandex.com",
        "protonmail.com", "tutanota.com", "fastmail.com", "gmail.com",
        "outlook.com", "hotmail.com", "aol.com",
        "banking.com", "chase.com", "wellsfargo.com", "bankofamerica.com",
        "citi.com", "capitalone.com", "paypal.com", "stripe.com",
        "venmo.com", "cash.app", "wise.com", "transferwise.com",
        "coinbase.com", "binance.com", "kraken.com",
        "nytimes.com", "washingtonpost.com", "theguardian.com", "bbc.co.uk",
        "cnn.com", "reuters.com", "apnews.com", "npr.org",
        "arxiv.org", "nature.com", "science.org", "springer.com",
        "ieee.org", "acm.org", "stackexchange.com",
        "imdb.com", "rottentomatoes.com", "metacritic.com",
        "weather.com", "accuweather.com",
        "maps.google.com", "maps.apple.com",
        "translate.google.com", "deepl.com",
        "archive.org", "web.archive.org",
        "linkedin.com", "angel.co", "indeed.com",
        "medium.com", "substack.com", "ghost.org",
        "figma.com", "canva.com", "notion.so",
        "airtable.com", "trello.com", "asana.com", "monday.com",
        "docs.google.com", "sheets.google.com", "slides.google.com",
        "drive.google.com", "photos.google.com",
        "mail.google.com", "calendar.google.com",
        "mega.nz", "pcloud.com", "onedrive.live.com"
    )

    // ==================== STATE ====================

    /** Total blocked requests counter (session lifetime). */
    private val _totalBlocked = AtomicLong(0)

    /** Per-category blocked counts. */
    private val _categoryBlocked = java.util.concurrent.ConcurrentHashMap<BlockCategory, AtomicLong>()

    /** Per-page cosmetic filter cache. */
    private val cosmeticFilterCache = object : LinkedHashMap<String, String>(50, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, String>?): Boolean {
            return size > 50
        }
    }

    /** Small LRU cache (50 entries) of parsed host strings. */
    private val hostCache = object : LinkedHashMap<String, String>(50, 0.75f, true) {
        override fun removeEldestEntry(eldest: MutableMap.MutableEntry<String, String>?): Boolean {
            return size > 50
        }
    }

    init {
        // Initialize per-category counters
        for (cat in BlockCategory.entries) {
            _categoryBlocked[cat] = AtomicLong(0)
        }
    }

    // ==================== PUBLIC API ====================

    /** Total blocked requests in the current session. */
    fun totalBlocked(): Long = _totalBlocked.get()

    /** Blocked count per category in the current session. */
    fun blockedByCategory(): Map<BlockCategory, Long> =
        BlockCategory.entries.associateWith { _categoryBlocked[it]?.get() ?: 0L }

    /** Reset all session statistics. */
    fun resetStats() {
        _totalBlocked.set(0)
        for (cat in BlockCategory.entries) {
            _categoryBlocked[cat]?.set(0)
        }
    }

    /** Whether the user has enabled the ad-blocker (default: true). */
    fun isEnabled(ctx: Context): Boolean = Prefs.getAdBlockEnabled(ctx)

    /** Check if a specific category is enabled. */
    fun isCategoryEnabled(ctx: Context, category: BlockCategory): Boolean {
        return Prefs.getAdBlockCategoryEnabled(ctx, category)
    }

    /**
     * Returns true if ad-blocking is enabled AND the URL matches a
     * blocked domain or URL pattern.
     */
    fun shouldBlock(ctx: Context, url: String): Boolean {
        if (!isEnabled(ctx)) return false
        if (isAd(url)) {
            _totalBlocked.incrementAndGet()
            return true
        }
        return false
    }

    /**
     * Convenience: checks [shouldBlock] for the given [WebResourceRequest].
     * Returns an empty response if blocked, or null if it should proceed normally.
     */
    fun interceptIfBlocked(ctx: Context, request: WebResourceRequest): WebResourceResponse? {
        // NEVER block main-frame navigations
        if (request.isForMainFrame) return null
        val url = request.url.toString()
        return if (shouldBlock(ctx, url)) emptyResponse() else null
    }

    /**
     * Returns true if the URL's host ends with (or equals) a blocked domain
     * OR matches a URL keyword pattern.
     */
    fun isAd(url: String): Boolean {
        val host = parseHost(url) ?: return false

        // Fast path: check each category's domain set
        for ((category, domains) in DOMAINS) {
            for (domain in domains) {
                if (host == domain || host.endsWith(".$domain")) {
                    _categoryBlocked[category]?.incrementAndGet()
                    return true
                }
            }
        }

        // Check URL keyword patterns
        val lowerUrl = url.lowercase()
        for (pattern in URL_PATTERNS) {
            if (lowerUrl.contains(pattern.lowercase())) {
                _categoryBlocked[BlockCategory.OTHER]?.incrementAndGet()
                return true
            }
        }

        return false
    }

    /**
     * Builds an empty [WebResourceResponse] used to silently drop an
     * ad/tracker request.
     */
    fun emptyResponse(): WebResourceResponse {
        return WebResourceResponse("text/plain", "utf-8", ByteArrayInputStream(ByteArray(0)))
    }

    /**
     * Returns JavaScript code to inject cosmetic CSS filters that hide
     * ad/tracker DOM elements. The result is cached per-page domain.
     */
    fun getCosmeticFilterJs(pageUrl: String): String {
        val domain = parseHost(pageUrl) ?: return ""
        return cosmeticFilterCache.getOrPut(domain) {
            buildCosmeticFilterJs()
        }
    }

    /**
     * Returns an HTTPS-upgraded URL if the domain is in our upgrade list.
     * Returns null if no upgrade is needed or the URL is already HTTPS.
     */
    fun upgradeToHttps(url: String): String? {
        if (url.startsWith("https://")) return null
        if (!url.startsWith("http://")) return null
        val host = parseHost(url) ?: return null
        for (httpsDomain in HTTPS_DOMAINS) {
            if (host == httpsDomain || host.endsWith(".$httpsDomain")) {
                return "https://${url.substring(7)}"
            }
        }
        return null
    }

    // ==================== INTERNAL ====================

    /** Parses the host from a URL string, using LRU cache. */
    private fun parseHost(url: String): String? {
        return hostCache.getOrPut(url) {
            try { Uri.parse(url).host ?: "" } catch (_: Exception) { "" }
        }.ifBlank { null }
    }

    /**
     * Builds the cosmetic filter JavaScript that creates a <style> element
     * with CSS rules to hide all matched ad/tracker DOM elements.
     */
    private fun buildCosmeticFilterJs(): String {
        val cssRules = COSMETIC_SELECTORS.joinToString(",\n") { "$it { display: none !important; visibility: hidden !important; height: 0 !important; min-height: 0 !important; max-height: 0 !important; overflow: hidden !important; pointer-events: none !important; }" }

        return """
        (function(){
            var id = '__pb_cosmetic_filter';
            if (document.getElementById(id)) return;
            var s = document.createElement('style');
            s.id = id;
            s.textContent = `$cssRules`;
            (document.head || document.documentElement).appendChild(s);
            // Re-apply periodically to catch dynamically injected ads
            var observer = new MutationObserver(function(mutations) {
                for (var i = 0; i < mutations.length; i++) {
                    for (var j = 0; j < mutations[i].addedNodes.length; j++) {
                        var node = mutations[i].addedNodes[j];
                        if (node.nodeType === 1) {
                            var selectors = `${COSMETIC_SELECTORS.joinToString(",")}`;
                            var matched = node.querySelectorAll ? node.querySelectorAll(selectors) : null;
                            if (matched && matched.length > 0) return;
                        }
                    }
                }
            });
            if (document.body) {
                observer.observe(document.body, { childList: true, subtree: true });
            } else {
                document.addEventListener('DOMContentLoaded', function() {
                    observer.observe(document.body, { childList: true, subtree: true });
                });
            }
            // Also apply on load
            if (document.readyState === 'complete' || document.readyState === 'interactive') {
                applySelectors();
            } else {
                window.addEventListener('load', applySelectors);
            }
            function applySelectors() {
                var all = document.querySelectorAll(`${COSMETIC_SELECTORS.joinToString(",")}`);
                for (var i = 0; i < all.length; i++) {
                    all[i].style.setProperty('display', 'none', 'important');
                }
            }
            // MutationObserver auto-applies via CSS rules
        })();
        """.trimIndent()
    }
}
